# Generated by Django 4.2.2 on 2023-06-06 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('distribution_expense', models.DecimalField(decimal_places=2, max_digits=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
    ]
